name: scrnaseq_vitamin_a
channels:
  - conda-forge
dependencies:
  - _r-mutex=1.0.1=anacondar_1
  - anndata=0.11.3=pyhd8ed1ab_0
  - anyio=4.8.0=pyhd8ed1ab_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py313h20a7fcf_5
  - arpack=3.9.1=nompi_h1f29f7c_102
  - array-api-compat=1.11=pyhd8ed1ab_0
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.4=pyhd8ed1ab_1
  - attrs=25.1.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.3=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - blosc=1.21.6=h7dd00d9_1
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.1.0=py313h3579c5c_2
  - brunsli=0.1=h9f76cd9_0
  - bwidget=1.10.1=hce30654_0
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.4=h5505292_0
  - c-blosc2=2.15.2=h9cbb436_1
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.4=h6a3b0d2_0
  - cctools_osx-arm64=1010.6=h3b4f5d3_6
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py313hc845a76_0
  - charls=2.4.2=h13dd4ca_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - clang=18.1.8=default_h474c9e2_10
  - clang-18=18.1.8=default_hf90f093_10
  - clang_impl_osx-arm64=18.1.8=h2ae9ea5_25
  - clang_osx-arm64=18.1.8=h07b0088_25
  - clangxx=18.1.8=default_h1ffe849_10
  - clangxx_impl_osx-arm64=18.1.8=h555f467_25
  - clangxx_osx-arm64=18.1.8=h07b0088_25
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - compiler-rt=18.1.8=h856b3c1_1
  - compiler-rt_osx-arm64=18.1.8=h832e737_1
  - contourpy=1.3.1=py313h0ebd0e5_0
  - curl=8.12.1=h73640d1_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.12=py313h928ef07_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.56.0=py313ha9b7d5b_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=hadb7bae_2
  - fribidi=1.0.10=h27ca646_0
  - gfortran_impl_osx-arm64=13.2.0=h252ada1_3
  - gfortran_osx-arm64=13.2.0=h57527a5_1
  - giflib=5.2.2=h93a5062_0
  - glpk=5.0=h6d7a090_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.13=hebf3989_1003
  - gsl=2.7=h6e638da_0
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.2.0=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py313hcdf59df_100
  - harfbuzz=10.4.0=hb72c1af_0
  - hdf5=1.14.3=nompi_ha698983_109
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2024.12.30=py313h4fccb6f_0
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=9.0.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - isl=0.26=imath32_h347afa1_101
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.5=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py313h8f79df9_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.3.5=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jxrlib=1.1=h93a5062_3
  - kiwisolver=1.4.7=py313hf9c7212_0
  - krb5=1.21.3=h237132a_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h7eeda09_0
  - ld64_osx-arm64=951.9=hb6b49e2_6
  - legacy-api-wrap=1.4.1=pyhd8ed1ab_0
  - lerc=4.0.0=h9a09cb3_0
  - libaec=1.1.3=hebf3989_0
  - libasprintf=0.24.1=h493aca8_0
  - libavif16=1.1.1=hf9d1e0e_3
  - libblas=3.9.0=35_h51639a9_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=35_hb0561ab_openblas
  - libclang-cpp18.1=18.1.8=default_hf90f093_10
  - libcurl=8.12.1=h73640d1_0
  - libcxx=19.1.7=ha82da77_0
  - libcxx-devel=18.1.8=h6dc3340_8
  - libdeflate=1.23=hec38601_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.6.4=h286801f_0
  - libffi=3.4.2=h3422bc3_5
  - libgettextpo=0.24.1=h493aca8_0
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran-devel_osx-arm64=13.2.0=h5d7a38c_3
  - libgfortran5=14.2.0=h6c33f7e_103
  - libglib=2.84.0=hdff4504_0
  - libhwloc=2.11.2=default_hbce5d74_1001
  - libhwy=1.1.0=h2ffa867_0
  - libiconv=1.18=hfe07756_1
  - libintl=0.24.1=h493aca8_0
  - libjpeg-turbo=3.0.0=hb547adb_1
  - libjxl=0.11.1=h562e088_0
  - liblapack=3.9.0=35_hd9741b5_openblas
  - libllvm15=15.0.7=h4429f82_5
  - libllvm18=18.1.8=default_hb458b26_5
  - liblzma=5.6.4=h39f12f2_0
  - libmpdec=4.0.0=h99b78c6_0
  - libnghttp2=1.64.0=h6d7220d_0
  - libopenblas=0.3.30=openmp_hf332438_0
  - libpng=1.6.47=h3783ad8_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.49.1=h3f77e49_1
  - libssh2=1.11.1=h9cc3647_0
  - libtiff=4.7.0=h551f018_3
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.14.0=h178c5d8_0
  - libzlib=1.3.1=h8359307_2
  - libzopfli=1.0.3=h9f76cd9_0
  - llvm-openmp=19.1.7=hdb05f8b_0
  - llvm-tools=18.1.8=default_hb458b26_5
  - llvm-tools-18=18.1.8=default_hb458b26_5
  - llvmlite=0.44.0=py313hd06b435_0
  - lz4-c=1.10.0=h286801f_1
  - make=4.4.1=hc9fafa5_2
  - markupsafe=3.0.2=py313ha9b7d5b_1
  - matplotlib=3.10.1=py313h39782a4_0
  - matplotlib-base=3.10.1=py313haaf02c0_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.2=pyhd8ed1ab_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - munkres=1.1.4=pyh9f0ad1d_0
  - natsort=8.4.0=pyh29332c3_1
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numba=0.61.0=py313h8aea8d6_1
  - numpy=2.1.3=py313hca4752e_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openpyxl=3.1.5=py313h90caf49_1
  - openssl=3.5.2=he92f556_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py313h47b39a6_1
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.56.2=h73f1e88_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=ha881caa_2
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py313hb37fac4_0
  - pip=25.0.1=pyh145f28c_0
  - pixman=0.46.0=h2f9eb0b_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.6=pyhd8ed1ab_1
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - psutil=7.0.0=py313h90d716c_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyobjc-core=11.0=py313hb6afeec_0
  - pyobjc-framework-cocoa=11.0=py313hb6afeec_0
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.2=h81fe080_101_cp313
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-igraph=0.11.8=py313h9aae418_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.13=5_cp313
  - pytz=2024.1=pyhd8ed1ab_0
  - pywavelets=1.8.0=py313h46657e6_0
  - pyyaml=6.0.2=py313ha9b7d5b_2
  - pyzmq=26.2.1=py313he6960b1_0
  - qhull=2020.2=h420ef59_5
  - r=4.4=r44hd8ed1ab_1008
  - r-base=4.4.3=h3dfa2b9_0
  - r-boot=1.3_31=r44hc72bb7e_0
  - r-class=7.3_23=r44h570997c_0
  - r-cli=3.6.5=r44h31118f2_0
  - r-cluster=2.1.8.1=r44he0ea626_0
  - r-codetools=0.2_20=r44hc72bb7e_1
  - r-digest=0.6.37=r44hd76f289_0
  - r-dotcall64=1.2=r44hf8db2fc_0
  - r-foreign=0.8_90=r44h570997c_0
  - r-future=1.49.0=r44h785f33e_0
  - r-future.apply=1.11.3=r44hc72bb7e_0
  - r-generics=0.1.4=r44hc72bb7e_0
  - r-globals=0.18.0=r44hc72bb7e_0
  - r-glue=1.8.0=r44h0d9a900_0
  - r-kernsmooth=2.23_26=r44h2c658ed_0
  - r-lattice=0.22_7=r44h570997c_0
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-listenv=0.9.1=r44hc72bb7e_1
  - r-mass=7.3_64=r44h570997c_0
  - r-matrix=1.7_3=r44hf6a007b_0
  - r-mgcv=1.9_3=r44he66de11_0
  - r-nlme=3.1_167=r44he0ea626_0
  - r-nnet=7.3_20=r44h570997c_0
  - r-parallelly=1.44.0=r44h570997c_0
  - r-progressr=0.15.1=r44hc72bb7e_0
  - r-rcpp=1.0.14=r44h31118f2_0
  - r-rcppeigen=0.3.4.0.2=r44h8c6f55f_0
  - r-recommended=4.4=r44hd8ed1ab_1007
  - r-rlang=1.1.6=r44h31118f2_0
  - r-rpart=4.1.24=r44h570997c_0
  - r-seuratobject=5.1.0=r44h31118f2_0
  - r-sp=2.2_0=r44h570997c_0
  - r-spam=2.11_1=r44h15958ca_0
  - r-spatial=7.3_18=r44h570997c_0
  - r-survival=3.8_3=r44h570997c_0
  - rav1e=0.6.6=h69fbcac_2
  - readline=8.2=h1d1bf99_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.23.1=py313hb5fa170_0
  - scanpy=1.10.4=pyhd8ed1ab_0
  - scikit-image=0.25.2=py313h668b085_0
  - scikit-learn=1.6.1=py313hecba28c_0
  - scipy=1.15.2=py313h9a24e0a_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - send2trash=1.8.3=pyh31c8845_1
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=75.8.2=pyhff2d567_0
  - sigtool=0.1.3=h44b9a77_0
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h98b9ce2_1
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.4=py313h93df234_0
  - stdlib-list=0.11.1=pyhd8ed1ab_0
  - svt-av1=3.0.0=h8ab69cd_0
  - tapi=1300.6.5=h03f4b80_0
  - tbb=2022.0.0=h0cbf7ec_0
  - terminado=0.18.1=pyh31c8845_0
  - texttable=1.7.0=pyhd8ed1ab_1
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tifffile=2025.2.18=pyhd8ed1ab_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tktable=2.10=h1e387b8_6
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py313h90d716c_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_1
  - typing_extensions=4.12.2=pyha770c72_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025a=h78e105d_0
  - umap-learn=0.5.7=py313h8f79df9_1
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.2.2=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.5=hc1bb282_7
  - zfp=1.0.1=h1c5d8ea_2
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=h8359307_2
  - zlib-ng=2.2.4=h13dfb9a_0
  - zstd=1.5.7=h6491c7d_1
  - pip:
      - adjusttext==1.3.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - arboreto==0.1.6
      - biothings-client==0.4.1
      - bokeh==3.7.3
      - boltons==25.0.0
      - click==8.2.0
      - cloudpickle==3.1.1
      - ctxcore==0.2.0
      - cytoolz==1.0.1
      - dask==2025.5.0
      - decoupler==2.1.1
      - dill==0.4.0
      - distributed==2025.5.0
      - docrep==0.3.2
      - frozendict==2.4.6
      - frozenlist==1.6.0
      - fsspec==2025.3.2
      - harmonypy==0.0.10
      - interlap==0.2.7
      - legendkit==0.3.6
      - leidenalg==0.10.2
      - locket==1.0.0
      - loompy==3.0.8
      - lz4==4.4.4
      - marsilea==0.5.5
      - msgpack==1.1.0
      - multidict==6.4.3
      - multiprocessing-on-dill==3.5.0a4
      - mygene==3.2.2
      - narwhals==1.39.1
      - numexpr==2.10.2
      - numpy-groupies==0.11.2
      - partd==1.4.2
      - propcache==0.3.1
      - pyarrow==20.0.0
      - pyscenic==0.12.1
      - rpy2==3.6.0
      - rpy2-rinterface==3.6.0
      - rpy2-robjects==3.6.0
      - session-info2==0.2.2
      - sortedcontainers==2.4.0
      - tblib==3.1.0
      - toolz==1.0.0
      - tzlocal==5.3.1
      - xyzservices==2025.4.0
      - yarl==1.20.0
      - zict==3.0.0
prefix: /Users/gatocor/miniforge3/envs/scrnaseq_vitamin_a
