name: anterior_mesoderm_gastruloids_RA_scRNAseq_analysis_simple_env
channels:
  - conda-forge
dependencies:
  - jupyterlab=4.3.5
  - matplotlib=3.10.1
  - numpy=2.1
  - scanpy=1.10.4
  - scipy=1.15.2
  - seaborn=0.13.2
  - python-igraph=0.11.8
  - openpyxl=3.1.5
  - r=4.4
  - r-seuratobject=5.1.0
  - libgfortran=5
  - libopenblas[version='>=0.3.26']
  - ipython
